In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [1]:
import pandas as pd

df = pd.read_csv('ncbirths.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'ncbirths.csv'

In [ ]:
df

,fage,mage,mature,weeks,premie,visits,marital,gained,weight,lowbirthweight,gender,habit,whitemom
0,NaN,13,younger mom,39.0,full term,10.0,not married,38.0,7.63,not low,male,nonsmoker,not white
1,NaN,14,younger mom,42.0,full term,15.0,not married,20.0,7.88,not low,male,nonsmoker,not white
2,19.0,15,younger mom,37.0,full term,11.0,not married,38.0,6.63,not low,female,nonsmoker,white
3,21.0,15,younger mom,41.0,full term,6.0,not married,34.0,8.00,not low,male,nonsmoker,white
4,NaN,15,younger mom,39.0,full term,9.0,not married,27.0,6.38,not low,female,nonsmoker,not white
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,47.0,42,mature mom,40.0,full term,10.0,married,26.0,8.44,not low,male,nonsmoker,not white
996,34.0,42,mature mom,38.0,full term,18.0,married,20.0,6.19,not low,female,nonsmoker,white
997,39.0,45,mature mom,40.0,full term,15.0,married,32.0,6.94,not low,female,nonsmoker,white
998,55.0,46,mature mom,31.0,premie,8.0,married,25.0,4.56,low,female,nonsmoker,not white
999,45.0,50,mature mom,39.0,full term,14.0,married,23.0,7.13,not low,female,nonsmoker,white

In [ ]:
df['premature'] = (df['weeks'] < 37).astype(int)

In [ ]:
contingency_table1 = pd.crosstab(df['habit'], df['premature'])
contingency_table1

premature    0    1
habit
nonsmoker  740  133
smoker     107   19

In [ ]:
import numpy as np


prem_smoker = 19
total_smoker = 126

prem_non = 133
total_non = 873


p1 = prem_smoker / total_smoker
p2 = prem_non / total_non

se = np.sqrt(p1*(1-p1)/total_smoker + p2*(1-p2)/total_non)


lower = (p1 - p2) - 1.96*se
upper = (p1 - p2) + 1.96*se

(lower, upper)

(np.float64(-0.06843147436259368), np.float64(0.06532232692354929))

In [ ]:
import statsmodels.api as sm

count = np.array([19, 133])
nobs = np.array([126, 873])

z_stat, p_value = sm.stats.proportions_ztest(count, nobs)
z_stat, p_value

(np.float64(-0.04541747240132055), np.float64(0.9637745543952178))

In [ ]:
df.groupby('habit')['weight'].agg(['mean', 'std', 'count'])

               mean       std  count
habit
nonsmoker  7.144273  1.518681    873
smoker     6.828730  1.386180    126

In [ ]:
import numpy as np
from scipy.stats import ttest_ind

smoker = df[df['habit'] == 'smoker']['weight']
nonsmoker = df[df['habit'] == 'nonsmoker']['weight']

print(len(smoker), len(nonsmoker))

t_stat, p_val = ttest_ind(smoker, nonsmoker, equal_var=False)
t_stat, p_val

126 873

(np.float64(-2.3590109449335013), np.float64(0.01945055644373227))

In [ ]:
res = ttest_ind(smoker, nonsmoker, equal_var=False)

res.df

np.float64(171.3246566624258)